apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: spark

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: spark
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec"]
    verbs: ["create", "get", "watch", "list", "delete", "deletecollection", "update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "watch", "list", "delete", "deletecollection", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "watch", "list", "delete", "deletecollection", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "get", "watch", "list", "delete", "deletecollection", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-rolebinding
  namespace: spark
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: spark
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
